### ISSUE TITLE
Problem reading PVK with HID Omnikey 3121

### ISSUE THREAD

**Issue by gpfreak** [Kaupisch-IT/eGK-KVK#1]
I have a the problem, that I couldn't read PVK cards. There is only Hex 6E in the bytes.

**Comment by daniel-richter** [comment]
As far as we know, the ability to read PKV cards depends on the card terminal - since there are significant differences between eGKs and KVKs (a PKV cards acts like a KVK), both in terms of hardware (memory versus processor card) and data structure. See the colum "KVK/PVK" in [tested card terminals](https://github.com/Kaupisch-IT/eGK-KVK#anbindung-an-kartenleseterminals).

What card terminal are you using?

Could you post the debug output your application generates (e.g. as shown in [sample data reading processes with return codes](https://github.com/Kaupisch-IT/eGK-KVK#beispielhafter-ablauf-von-auslesevorg%C3%A4ngen-mit-r%C3%BCckgabecodes))?

**Comment by gpfreak** [comment]
We are using the HID Omnikey 3121 as Cardterminal. IT produces the folowing output
ResetCT     9000 	(Reset successful)
RequestICC  9000 	(Synchronous ICC presented, reset successful)
SelectEGK   6e00 	(Error: Falsches/unbekanntes Class-Byte)
SelectKVK   6e00 	(Error: Falsches/unbekanntes Class-Byte)
EjectICC    9000 	(Command successful)

**Comment by Kaupisch-IT** [comment]
Does the reading of eGKs work?  
Are other applications able to read PKV cards with this card terminal?

Can you try to skip the execution of `SelectEGK` and `SelectKVK` and call `ReadKKV` directly after `RequestICC` (`CardTerminalClient.cs`/`public static CardResult ReadCard`) and post the output here?

If that won't work: Can you try to change `0x00, // CLA` to `0xFF, // CLA` in `ReadKVK` and/or `SelectKVK` (and post the output).

**Comment by Kaupisch-IT** [comment]
Perhaps another shot: Have you tried to turn it (the terminal) off and on again? 

There are some terminals that don't like it when the commands are not (always) executed completely in the intended order (e.g. because you debug and terminate your application before it finished). After that, odd error messages came up.

The solution was to disconnect the device completely from the power supply and restart it. After that the application ran again without errors.

**Comment by jorisoft** [comment]
Hi, I have also a problem reading the KVK / PVK with an Cherry ST2100 Terminal. I understand that the ST2100 is compatible with the mentioned ST2052 from the author of this solution, so it should be able to read the KVK. ResetCT works great, but RequestICC return 6400 (dont know where to lookup the error behind this code) When I ignore this and try to continue with SelectKVK I get the error ERR_Host, if I ommit RequestICC and try to read the card I get the same ERR_HOST exception. Any idea ? Cherry said in their doc, that they can read both type of cards, however when I use their tool PCSC Diagnosetool and enter the KV in the field AVR, it says error and no card displays are displayed. I tried two different KVK cards no difference, any help would be appreciated. Changing all 0x00 with 0xFF in selectKVK or ReadKVK doesnt help...
Thank you for your ideas !

**Comment by jorisoft** [comment]
In your listing of tested terminals I see that ST2052 used ctpcsc32kv.dll, the ST2100 uses CTcym.dll (which doesnt work for Cherry Keyboard for KVK cards)

**Comment by jorisoft** [comment]
Here is the debug from the cherry log utility : 

0x2000;29.06.2021 15:26:16:865;;DllMain -> Process Attach;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:866;;Execution of CT_init with Params: Ctn=1, pn=1;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:866;;**** CtCym => C:\Users\orenz\Desktop\Test\SampleApp\bin\Debug\ctcym.dll V2.2.0.7 ****;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:867;;**** OS = Windows Unknown 64bit Professional, Version 6.02, Product = 0x1, Suite = 0x100 (Build 9200), x64 Proc ****;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:867;;CTCYM no cherry lib name = ;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:867;;**** Calling App = C:\Users\orenz\Desktop\Test\SampleApp\bin\Debug\SampleApp.exe V1.0.0.0, ProcessID = 15296 ****;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:16:867;TAL;CTransportLayer construction
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:870;TAL;CTransportLayer::TSProtocol, pfnQueryS.. = 744953a0, pfnFreem...= 744924a0
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:870;TAL;CTransportLayer::TSProtocol, QuerySessionID = 1
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:874;TAL;CTransportLayer::TSProtocol, leaving returns = 0
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:874;TAL;CTransportLayer destruction
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:874;Config;load config from C:\ProgramData\Cherry\CtApi\ctcym.xml;0x0;0x3BC0;0x5A1C;..\common\cconfiguration.cpp;154
0x0004;29.06.2021 15:26:16:874;Config;--> XML File successfully parsed;0x0;0x3BC0;0x5A1C;..\common\cconfiguration.cpp;158
0x0004;29.06.2021 15:26:16:874;Config;-> configured found device;0x0;0x3BC0;0x5A1C;..\common\cconfiguration.cpp;240
0x0004;29.06.2021 15:26:16:874;CtApi;open new session;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;280
0x2000;29.06.2021 15:26:16:874;;Open device;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:874;;Use CPCSCDevice;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:16:879;CtApi;->device found;0x0;0x3BC0;0x5A1C;..\common\cpcscdevice.cpp;88
0x0004;29.06.2021 15:26:16:879;CtApi;CSession->Open, lRet = ;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;292
0x0004;29.06.2021 15:26:16:879;CtApi;session opened successfully;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;295
0x2000;29.06.2021 15:26:16:881;;Execution of CT_Data with params: Ctn=1, dad=1, sad=2, lenc=5, command=20 11 00 00 00 , lenr=65535;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:16:881;CtApi;ExecuteCmd;0x0;0x3BC0;0x5A1C;..\common\cpcscdevice.cpp;177
0x0004;29.06.2021 15:26:16:881;CtApi;CBCSCommand_ResetCT::ExecuteCmd;0x0;0x3BC0;0x5A1C;.\bcscommand_resetct.cpp;35
0x0004;29.06.2021 15:26:16:881;CtApi;CT_data ExecuteCmd returned;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;347
0x2000;29.06.2021 15:26:16:881;;CT_Data Response: 90 00 ;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:881;;Execution of CT_Data returned with: 0;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:895;;Execution of CT_Data with params: Ctn=1, dad=1, sad=2, lenc=5, command=20 12 01 00 00 , lenr=65535;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:16:895;CtApi;ExecuteCmd;0x0;0x3BC0;0x5A1C;..\common\cpcscdevice.cpp;177
0x0004;29.06.2021 15:26:16:895;CtApi;CBCSCommand_RequestICC::ExecuteCmd;0x0;0x3BC0;0x5A1C;.\bcscommand_requesticc.cpp;20
0x0004;29.06.2021 15:26:16:895;CtApi;call SCardGetStatusChange, returned with;0x0;0x3BC0;0x5A1C;.\bcscommand_requesticc.cpp;176
0x0004;29.06.2021 15:26:16:896;CtApi;CT_data ExecuteCmd returned;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;347
0x2000;29.06.2021 15:26:16:896;;CT_Data Response: 64 00 ;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:896;;Execution of CT_Data returned with: 0;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:17:741;;Execution of CT_Data with params: Ctn=1, dad=0, sad=2, lenc=11, command=00 A4 04 00 06 D2 76 00 00 01 01 , lenr=65535;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:17:741;CtApi;ExecuteCmd;0x0;0x3BC0;0x5A1C;..\common\cpcscdevice.cpp;177
0x0004;29.06.2021 15:26:17:741;CtApi;CICCCommand_Common::ExecuteCmd;0x0;0x3BC0;0x5A1C;.\icccommand_common.cpp;38
0x0004;29.06.2021 15:26:17:743;CtApi;CT_data ExecuteCmd returned;0xFFFFFF81;0x3BC0;0x5A1C;.\csessionhandler.cpp;347
0x2000;29.06.2021 15:26:17:743;;Execution of CT_Data returned with: -127;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:20:695;;Execution of CT_close with Params: Ctn=1;0x0;0x3BC0;0x5A1C;;0

**Comment by Kaupisch-IT** [comment]
I managed to get access to an HID Omnikey 3121. Since I could not manage to install the CT-API for this terminal (and thus the CT-API-DLL "ctdeutin.dll" could not be installed either), I contacted the HID support. They wrote:

> Unfortunately, we would not look to support CT-API anymore. The purpose of the API was to support German Gesundheitskarte, based on a storage card back when it was introduced. For quite some time, current cards have been processor-based and need to be integrated directly via PC/SC.
> I am sorry that this does not fit with your software application.

How did you get the CT API for the Omnikey to work? Could you provide your ctdeutin.dll?

**Comment by gpfreak** [comment]
The ctdeutin.dll I get from old drivers. At the moment I use the ct dll from cherry keyboard card reader. This dll theems to be compatible

**Comment by Kaupisch-IT** [comment]
Thanks for the tip! I could get my Omnikey 3121 USB to work (at least with eGK) with the CT-API provided by CHERRY (`CTChyCTApiSp.dll`, `ctcym.dll`). I can read eGKs but run into the same errors with KVK ("Error: Falsches/unbekanntes Class-Byte").

Therefore, I would assume that the reading of PKV cards (former KVK) is not possible with HID Omnikey 3121 USB.

**Comment by Kaupisch-IT** [comment]
Annother comment from HID Support is:

> Unfortunately, I can only confirm that we don't provide a CT-API DLL for the latest generation of OMNIKEY 3121 readers. The readers fully support KVK and eGK though. It is also possible to develop a CT-API library that supports our Aviator chipset. This is very likely what you see in the library provided by Cherry.
> Please note that OMNIKEY 3121 readers fully support synchronous cards directly via PC/SC-level APDU exchange. Unlike CT-API and our very own synchronous API, this works flawlessly across multiple platforms and can even be done on zero clients without any additional third-party libraries
