### ISSUE TITLE
Reading KVK/PVK with an Cherry ST2100 Terminal

### ISSUE THREAD

**Issue by Kaupisch-IT** [Kaupisch-IT/eGK-KVK#3]
Hi, I have also a problem reading the KVK / PVK with an Cherry ST2100 Terminal. I understand that the ST2100 is compatible with the mentioned ST2052 from the author of this solution, so it should be able to read the KVK. ResetCT works great, but RequestICC return 6400 (dont know where to lookup the error behind this code) When I ignore this and try to continue with SelectKVK I get the error ERR_Host, if I ommit RequestICC and try to read the card I get the same ERR_HOST exception. Any idea ? Cherry said in their doc, that they can read both type of cards, however when I use their tool PCSC Diagnosetool and enter the KV in the field AVR, it says error and no card displays are displayed. I tried two different KVK cards no difference, any help would be appreciated. Changing all 0x00 with 0xFF in selectKVK or ReadKVK doesnt help...
Thank you for your ideas !

_Originally posted by @jorisoft in https://github.com/Kaupisch-IT/eGK-KVK/issues/1#issuecomment-870687319_

**Comment by Kaupisch-IT** [comment]
In your listing of tested terminals I see that ST2052 used ctpcsc32kv.dll, the ST2100 uses CTcym.dll (which doesnt work for Cherry Keyboard for KVK cards)

_Originally posted by @jorisoft in https://github.com/Kaupisch-IT/eGK-KVK/issues/1#issuecomment-870688843_

**Comment by Kaupisch-IT** [comment]
Here is the debug from the cherry log utility : 

0x2000;29.06.2021 15:26:16:865;;DllMain -> Process Attach;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:866;;Execution of CT_init with Params: Ctn=1, pn=1;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:866;;**** CtCym => C:\Users\orenz\Desktop\Test\SampleApp\bin\Debug\ctcym.dll V2.2.0.7 ****;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:867;;**** OS = Windows Unknown 64bit Professional, Version 6.02, Product = 0x1, Suite = 0x100 (Build 9200), x64 Proc ****;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:867;;CTCYM no cherry lib name = ;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:867;;**** Calling App = C:\Users\orenz\Desktop\Test\SampleApp\bin\Debug\SampleApp.exe V1.0.0.0, ProcessID = 15296 ****;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:16:867;TAL;CTransportLayer construction
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:870;TAL;CTransportLayer::TSProtocol, pfnQueryS.. = 744953a0, pfnFreem...= 744924a0
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:870;TAL;CTransportLayer::TSProtocol, QuerySessionID = 1
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:874;TAL;CTransportLayer::TSProtocol, leaving returns = 0
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:874;TAL;CTransportLayer destruction
;0x0;0x3BC0;0x5A1C;ctcym\common\win\transportlayer.h;64
0x0004;29.06.2021 15:26:16:874;Config;load config from C:\ProgramData\Cherry\CtApi\ctcym.xml;0x0;0x3BC0;0x5A1C;..\common\cconfiguration.cpp;154
0x0004;29.06.2021 15:26:16:874;Config;--> XML File successfully parsed;0x0;0x3BC0;0x5A1C;..\common\cconfiguration.cpp;158
0x0004;29.06.2021 15:26:16:874;Config;-> configured found device;0x0;0x3BC0;0x5A1C;..\common\cconfiguration.cpp;240
0x0004;29.06.2021 15:26:16:874;CtApi;open new session;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;280
0x2000;29.06.2021 15:26:16:874;;Open device;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:874;;Use CPCSCDevice;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:16:879;CtApi;->device found;0x0;0x3BC0;0x5A1C;..\common\cpcscdevice.cpp;88
0x0004;29.06.2021 15:26:16:879;CtApi;CSession->Open, lRet = ;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;292
0x0004;29.06.2021 15:26:16:879;CtApi;session opened successfully;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;295
0x2000;29.06.2021 15:26:16:881;;Execution of CT_Data with params: Ctn=1, dad=1, sad=2, lenc=5, command=20 11 00 00 00 , lenr=65535;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:16:881;CtApi;ExecuteCmd;0x0;0x3BC0;0x5A1C;..\common\cpcscdevice.cpp;177
0x0004;29.06.2021 15:26:16:881;CtApi;CBCSCommand_ResetCT::ExecuteCmd;0x0;0x3BC0;0x5A1C;.\bcscommand_resetct.cpp;35
0x0004;29.06.2021 15:26:16:881;CtApi;CT_data ExecuteCmd returned;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;347
0x2000;29.06.2021 15:26:16:881;;CT_Data Response: 90 00 ;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:881;;Execution of CT_Data returned with: 0;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:895;;Execution of CT_Data with params: Ctn=1, dad=1, sad=2, lenc=5, command=20 12 01 00 00 , lenr=65535;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:16:895;CtApi;ExecuteCmd;0x0;0x3BC0;0x5A1C;..\common\cpcscdevice.cpp;177
0x0004;29.06.2021 15:26:16:895;CtApi;CBCSCommand_RequestICC::ExecuteCmd;0x0;0x3BC0;0x5A1C;.\bcscommand_requesticc.cpp;20
0x0004;29.06.2021 15:26:16:895;CtApi;call SCardGetStatusChange, returned with;0x0;0x3BC0;0x5A1C;.\bcscommand_requesticc.cpp;176
0x0004;29.06.2021 15:26:16:896;CtApi;CT_data ExecuteCmd returned;0x0;0x3BC0;0x5A1C;.\csessionhandler.cpp;347
0x2000;29.06.2021 15:26:16:896;;CT_Data Response: 64 00 ;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:16:896;;Execution of CT_Data returned with: 0;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:17:741;;Execution of CT_Data with params: Ctn=1, dad=0, sad=2, lenc=11, command=00 A4 04 00 06 D2 76 00 00 01 01 , lenr=65535;0x0;0x3BC0;0x5A1C;;0
0x0004;29.06.2021 15:26:17:741;CtApi;ExecuteCmd;0x0;0x3BC0;0x5A1C;..\common\cpcscdevice.cpp;177
0x0004;29.06.2021 15:26:17:741;CtApi;CICCCommand_Common::ExecuteCmd;0x0;0x3BC0;0x5A1C;.\icccommand_common.cpp;38
0x0004;29.06.2021 15:26:17:743;CtApi;CT_data ExecuteCmd returned;0xFFFFFF81;0x3BC0;0x5A1C;.\csessionhandler.cpp;347
0x2000;29.06.2021 15:26:17:743;;Execution of CT_Data returned with: -127;0x0;0x3BC0;0x5A1C;;0
0x2000;29.06.2021 15:26:20:695;;Execution of CT_close with Params: Ctn=1;0x0;0x3BC0;0x5A1C;;0

_Originally posted by @jorisoft in https://github.com/Kaupisch-IT/eGK-KVK/issues/1#issuecomment-870701510_

**Comment by Kaupisch-IT** [comment]
First things first: What type of card have you tried? KVK or eGK? Is there any KVK or eGK card that worked?  
How does the DEBUG output of the sample app look like? 

Error codes can be found in [KaupischIT.CardReader/CardTerminalClient.cs](https://github.com/Kaupisch-IT/eGK-KVK/blob/master/KaupischIT.CardReader/CardTerminalClient.cs). The VisualStudio output window should display all executed commands, result codes and result descriptions.  
`6400` is `Error: Reset not successful`

**Comment by jorisoft** [comment]
Thank you very much for your reply and time.
First of all I see that I see that I used an outdated version of your solution sorry. Now I am using the most current one but I am still not able to get the KVK/PVK to be read, here is the output : 

ResetCT     9000 	(Reset successful)
RequestICC  6400 	(Error: Reset not successful)
Exception thrown: 'KaupischIT.CardReader.CtException' in KaupischIT.CardReader.dll
An unhandled exception of type 'KaupischIT.CardReader.CtException' occurred in KaupischIT.CardReader.dll
Vom Host/Betriebssystem wurde dem HTSI ein Fehler signalisiert, was einen Funktionsabbruch zur Folge hat; Neuinitialisierung des CT erforderlich

It has no effect I unplug the device and try again. When using the EGK it paritally works, the contents is read but I get the following output : 
ResetCT     9000 	(Reset successful)
RequestICC  9001 	(Asynchronous ICC presented, reset successful)
SelectEGK   9000 	(Command successful - erfolgreiche Selektion eines Files)
ReadEGK     9000 	(Command successful - Datei gelesen)
ReadEGK     9000 	(Command successful - Datei gelesen)
<?xml version="1.0" encoding="ISO-8859-15" standalone="yes"?><UC_PersoenlicheVersichertendatenXML CDM_VERSION="5.1.0" ...contents of the card here....
Exception thrown: 'System.ArgumentException' in mscorlib.dll
An unhandled exception of type 'System.ArgumentException' occurred in mscorlib.dll
Das Quellarray ist nicht lang genug. Überprüfen Sie srcIndex, die Länge und die Untergrenze des Arrays.

The issues is in the method 
private void DecodeVD(byte[] bytes)  length of bytes in this sample is 608
but 
   int offsetEndGVD = (bytes[6]<<8) + bytes[7]; returns 611 which causes an exception in Array.copy.
I get over it by adding this line : 
if (offsetEndGVD > bytes.Length)
  offsetEndGVD = bytes.Length;

**Comment by jorisoft** [comment]
I solved the issue by installing a newer Cherry software and not using the CTCYM.dll but ctpcsc32kv.dll. Therefore I can confirm that the Cherry ST-2100 Reader works with eGK and KVK now

**Comment by Kaupisch-IT** [comment]
Okay, so we have two problems here...

- **ArgumentException with EGK**: Hm, interesting. That's a very specific error - what Krankenkasse is it? All cards we tested returned the correct data offsets (`offsetEndGVD` is part of the data saved on the card)...
- **RequestICC error with KVK**: Do you have multiple KVKs to test? Is it a PVK-Card (Privatversicherung)? Looks like your terminal does not like this card.

**Comment by Kaupisch-IT** [comment]
*Exception in DecodeVD*: Interesting... the data stored returns an offset beyond the data's lengts. What Krankenkasse is it?  
e6418fe4f3c6266c94e5f2377726731f5e7acadb should fix it.

Thank's!

**Comment by jorisoft** [comment]
Many thanks for all your assistance ! It was a PVK Barmenia card (quite old)

**Comment by poiuztreq** [comment]
> Many thanks for all your assistance ! It was a PVK Barmenia card (quite old)

Would it be possible for you to share the source code you’re using?
I’m currently struggling to establish a connection to the ST-2100 card terminal, and reviewing your implementation would help me pinpoint what I’m missing and get the integration running smoothly.
